### ISSUE TITLE
Kit names and HLA file names

### ISSUE THREAD

**Issue by TheArtisanBG** [Argent77/A7-add_kit_ex#7] opened 2024-04-29 07:59 UTC
I seem to have run into an issue where if the internal name of a kit is the same as the HLA 2da file minus the lu**** part, it won't add the HLA to the luabbr.2da table. So for example when I have C0SAFM and LUC0SAFM.2DA it won't work. I changed the kit name to C0_SA_FIGHTER_MAGE, it then works.

**Comment by Argent77** [comment] 2024-04-29 09:02
I can confirm this issue. It looks like the entry is added to `luabbr.2da` with the table's default value (`*`) in this case. I'll look into it.

**Comment by Argent77** [comment] 2024-04-29 10:06
Fixed by a724ef4.

**Closed as completed by Argent77** 2024-04-29 10:06 UTC
